In [1]:
import numpy as np
import time
import random

def task_1(dimension,f_type):
    def task_default():
        matrix = []
        for i in range(dimension):
            row = []
            for j in range(dimension):
                if i == j:
                    row.append(i + 1)
                else:
                    row.append(0)
            matrix.append(row)
        return matrix
    
    def task_numpy():
        matrix = np.zeros((dimension, dimension), dtype=int)
        diagonal_values = np.arange(1, dimension+1)
        np.fill_diagonal(matrix, diagonal_values)
        return matrix
    
    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [2]:
def task_2(n, f_type):
     
    def task_default():
        pattern = [[(i + j) % 2 for j in range(n)] for i in range(n)]

        matrix = [[0 for _ in range(n)] for _ in range(n)]

        matrix[0:n:2] = pattern[0:n:2]
        matrix[1:n:2] = pattern[1:n:2]
        return matrix

    def task_numpy():
        print([[(i + j) % 2 for j in range(n)] for i in range(n)])

        matrix = np.zeros((n, n))

        matrix[1::2, ::2] = 1
        matrix[::2, 1::2] = 1

        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [3]:
def task_4(n, m, f_type):

    def task_default():
        return [[i if j == 0 else 0 for i in range(n)] for j in range(m)]

    def task_numpy():
        matrix = np.zeros((m, n))
        matrix[0] = np.arange(n)
        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [4]:
def task_7(arr,f_type):
    def task_default():
        for i in arr:
            if arr[i] == 0:
                arr[i]=-1
        return arr
    
    def task_numpy():
        arr_np=np.array(arr)
        arr_np[arr_np==0]=-1
        return arr_np
    
    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [5]:
def task_8(arr, f_type):

    def task_default():
        zeros = len(list(filter(lambda x: x == 0, arr)))
        nonezeros = len(list(filter(lambda x: x != 0, arr)))

        return [nonezeros, zeros]

    def task_numpy():
        nonezeros =np.count_nonzero(arr)
        zeros = np.count_nonzero(arr==0)
        return [nonezeros, zeros]

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [6]:
def task_12(n, f_type):

    def task_default():
        return [[0 if (j == 0 or i == 0 or j == n-1 or i == n-1) else 1 for i in range(n)] for j in range(n)]

    def task_numpy():
        matrix = np.zeros((n, n))
        matrix[1:-1, 1:-1] = 1

        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]


In [7]:
def task_15(n, f_type):

    def task_default():
        return [[0 if i % 2 == 0 else 1 for i in range(n)] for _ in range(n)]

    def task_numpy():
        matrix = np.zeros((n, n))
        matrix[::, 1::2] = 1
        return matrix

    f = {'default': task_default, 'numpy': task_numpy}

    return f[f_type]

In [8]:
def task_16(n,f_type):
    def task_default():
        return [0 if n / 4 < i < 3 * n / 4 else i for i in range(n)]
    
    def task_numpy():
        vector = np.arange(n)  
        mask = (vector > n/4) & (vector < 3*n/4)  
        vector[mask] = 0  
        return vector
        
    f = {'default': task_default, 'numpy': task_numpy}
    return f[f_type]

In [9]:
def task_20(n,f_type):
    def task_default():
        
        return max([random.random() for _ in range(n)])
    
    def task_numpy():
        return np.max(np.random.rand(1,n))
        
    f = {'default': task_default, 'numpy': task_numpy}
    return f[f_type]

In [10]:
def compare_time(f1, f2):
    start = time.time()
    result1 = f1()
    end = time.time()

    print(result1)
    print(f"Execution time: {end - start} seconds")

    start = time.time()
    result2 = f2()
    end = time.time()

    print(result2)
    print(f"Execution time: {end - start} seconds")

    print(f"Results are equal:{np.allclose(result1, result2)}")

In [11]:
print("-----------task1-----------")
compare_time(task_1(5, 'default'), task_1(5, 'numpy'))
print("---------------------------\n")



-----------task1-----------
[[1, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 3, 0, 0], [0, 0, 0, 4, 0], [0, 0, 0, 0, 5]]
Execution time: 0.0 seconds
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
Execution time: 0.0 seconds
Results are equal:True
---------------------------



In [12]:
print("-----------task2-----------")
compare_time(task_2(5, 'default'), task_2(5, 'numpy'))
print("---------------------------\n")

-----------task2-----------
[[0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0]]
Execution time: 0.0 seconds
[[0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0], [1, 0, 1, 0, 1], [0, 1, 0, 1, 0]]
[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]
Execution time: 0.0 seconds
Results are equal:True
---------------------------



In [13]:
print("-----------task4-----------")
compare_time(task_4(3, 4, 'default'), task_4(3, 4, 'numpy'))
print("---------------------------\n")

-----------task4-----------
[[0, 1, 2], [0, 0, 0], [0, 0, 0], [0, 0, 0]]
Execution time: 0.0 seconds
[[0. 1. 2.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Execution time: 0.0 seconds
Results are equal:True
---------------------------



In [14]:
print("-----------task7-----------")
compare_time(task_7([1,0,2,0,3,0,4], 'default'), task_7([1,0,2,0,3,0,4], 'numpy'))
print("---------------------------\n")

-----------task7-----------
[1, -1, 2, -1, 3, 0, 4]
Execution time: 0.0 seconds
[ 1 -1  2 -1  3 -1  4]
Execution time: 0.0 seconds
Results are equal:False
---------------------------



In [15]:
print("-----------task8-----------")
compare_time(task_8([3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0], 'default'), task_8([3, 4, 0, 9, 8, 2, 4, 0, 8, 4, 0], 'numpy'))
print("---------------------------\n")

-----------task8-----------
[8, 3]
Execution time: 0.0 seconds
[8, 0]
Execution time: 0.0005581378936767578 seconds
Results are equal:False
---------------------------



In [16]:
print("-----------task12-----------")
compare_time(task_12(5, 'default'), task_12(5, 'numpy'))
print("---------------------------\n")

-----------task12-----------
[[0, 0, 0, 0, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 1, 1, 1, 0], [0, 0, 0, 0, 0]]
Execution time: 0.0 seconds
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
Execution time: 0.0 seconds
Results are equal:True
---------------------------



In [17]:
print("-----------task15-----------")
compare_time(task_15(5, 'default'), task_15(5, 'numpy'))
print("---------------------------\n")

-----------task15-----------
[[0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0], [0, 1, 0, 1, 0]]
Execution time: 0.0 seconds
[[0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0.]]
Execution time: 0.0 seconds
Results are equal:True
---------------------------



In [18]:
print("-----------task20-----------")
compare_time(task_20(10, 'default'), task_20(10, 'numpy'))
print("---------------------------\n")

-----------task20-----------
0.9087220821307619
Execution time: 0.0 seconds
0.8099008994237076
Execution time: 0.0 seconds
Results are equal:False
---------------------------



In [19]:
coefficients = np.array([[1, 2, 1, 1], [2, 1, 1, 1], [1, -1, 2, 1], [1, 1, -1, 3]])
constants = np.array([8, 5, -1, 10])
determinant = np.linalg.det(coefficients)

if determinant != 0:
    solutions = []
    for i in range(coefficients.shape[1]):
        temp = coefficients.copy()
        temp[:, i] = constants
        solutions.append(round(np.linalg.det(temp) / determinant, 2))
    print("Kramer's solutions:", solutions)

    mm_result = np.dot(coefficients, solutions)
    print("Matrix multiplication result:", mm_result)
    
    inv_result = np.dot(np.linalg.inv(coefficients), constants)
    print("Inverted matrix result:", inv_result)
    solve_result = np.linalg.solve(coefficients, constants)
    print("Solve function result:", solve_result)
    
    print("Are all solutions equal?", np.allclose(solutions, inv_result) and np.allclose(solutions, solve_result) and np.allclose(inv_result, solve_result))
else:
    print("The system of equations has no unique solutions.")


Kramer's solutions: [-0.05, 2.95, -0.16, 2.32]
Matrix multiplication result: [ 8.01  5.01 -1.   10.02]
Inverted matrix result: [-0.05263158  2.94736842 -0.15789474  2.31578947]
Solve function result: [-0.05263158  2.94736842 -0.15789474  2.31578947]
Are all solutions equal? False


In [20]:
def multiply(A, B):
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C


def add(A, B):
    m, n = A.shape
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
                C[i][j] += A[i][j] + B[i][j]
    return C


def subtract(A, B):
    m, n = A.shape
    C = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
                C[i][j] += A[i][j] - B[i][j]
    return C

A = np.array([[7, 2, 0], [-7, -2, 1], [1, 1, 0]])
B = np.array([[0, 2, 3], [1, 0, -2], [3, 1, 1]])

start = time.time()

result1 = np.dot(np.subtract(np.linalg.matrix_power(A, 2), np.linalg.matrix_power(B, 2)), np.add(A, B))

end = time.time()

print(result1)
print(f"Execution time: {end - start} seconds")

start = time.time()

result2 = multiply(subtract(multiply(A, A), multiply(B, B)), add(A, B))

end = time.time()

print(result2)
print(f"Execution time: {end - start} seconds")

print(f"Results are equal:{np.allclose(result1, result2)}")

[[ 138   88   68]
 [-154 -100  -78]
 [ -14  -16  -12]]
Execution time: 0.0 seconds
[[ 138.   88.   68.]
 [-154. -100.  -78.]
 [ -14.  -16.  -12.]]
Execution time: 0.008045196533203125 seconds
Results are equal:True
